name: shamcash
description: A simple wallet app built manually inside GitHub Codespaces.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
